### ISSUE TITLE
Store the guest and their respective ingredient contributions

### ISSUE THREAD

**Issue by OrestisBollano** [sopra-fs23-group-03/sopra-fs23-group-03-server#58]

**Comment by wlany** [comment]
possibly done already

**Comment by akkuebler** [comment]
Some as dev task #104 and done by commit [195e0c1](https://github.com/sopra-fs23-group-03/sopra-fs23-group-03-server/commit/195e0c17d8ca8a19d764c99b7abd2ee4ca545533)
